name: Android CI

on:
  push:
    branches:
      - '*'
    paths:
      - 'android/**'
      - 'root-module-manual/**'
  pull_request:
    paths:
      - 'android/**'
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to build
        required: true
        default: main
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.vars.outputs.short_sha }}
      app_version: ${{ steps.version.outputs.app_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - name: Decode keystore
        if: github.event_name != 'pull_request'
        run: echo "${{ secrets.RELEASE_KEYSTORE_FILE }}" | base64 --decode > android/release.keystore
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Accept Licenses
        run: yes | sdkmanager --licenses
      - name: Install NDK
        run: sdkmanager "ndk;30.0.14904198"
      - name: Create local.properties
        if: github.event_name != 'pull_request'
        env:
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: |
          printf 'sdk.dir=/usr/local/lib/android/sdk\n' > android/local.properties
          printf 'RELEASE_STORE_FILE=../release.keystore\n' >> android/local.properties
          printf 'RELEASE_STORE_PASSWORD=%s\n' "$RELEASE_STORE_PASSWORD" >> android/local.properties
          printf 'RELEASE_KEY_ALIAS=%s\n' "$RELEASE_KEY_ALIAS" >> android/local.properties
          printf 'RELEASE_KEY_PASSWORD=%s\n' "$RELEASE_KEY_PASSWORD" >> android/local.properties
      - name: Build debug APK for PRs
        if: github.event_name == 'pull_request'
        run: ./gradlew assembleFossDebug
        working-directory: android
      - name: Build FOSS release APK
        if: github.event_name != 'pull_request'
        run: ./gradlew assembleFossRelease
        working-directory: android
      - name: Get app version
        id: version
        run: echo "app_version=$(grep 'appVersionName =' android/app/build.gradle.kts | sed 's/.*= \"\(.*\)\"/\1/')" >> $GITHUB_OUTPUT
      - id: vars
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        if: github.event_name != 'pull_request'
        with:
          name: apk-release
          path: android/app/build/outputs/apk/foss/release/*.apk
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        if: github.event_name == 'pull_request'
        with:
          name: apk-debug
          path: android/app/build/outputs/apk/foss/debug/app-foss-debug.apk



  release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/download-artifact@v4
        with:
          name: apk-release
          path: artifacts/apk-release
      - id: prev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=$(gh release list \
            --limit 1 \
            --json tagName \
            --jq '.[0].tagName')

          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - id: changelog
        run: |
          if [ -z "${{ steps.prev.outputs.tag }}" ]; then
            NOTES=$(git log --pretty=format:"- %s ([%h](https://github.com/GARFIELD5211/Auris/commit/%H))")
          else
            NOTES=$(git log ${{ steps.prev.outputs.tag }}..HEAD --pretty=format:"- %s ([%h](https://github.com/GARFIELD5211/Auris/commit/%H))")
          fi
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          echo "$NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - id: tag
        run: echo "tag=nightly-${{ needs.build.outputs.short_sha }}" >> $GITHUB_OUTPUT

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.tag.outputs.tag }}" \
            artifacts/**/* \
            -t "Nightly ${{ needs.build.outputs.short_sha }}" \
            --notes "${{ steps.changelog.outputs.notes }}" \
            --prerelease
